# Generated by Django 3.0.2 on 2020-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='emails',
            field=models.EmailField(default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
