# Generated by Django 3.0.2 on 2020-05-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200516_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='emails',
            new_name='mam',
        ),
    ]
