# Generated by Django 3.0.2 on 2020-05-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200516_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='mam',
            new_name='emails',
        ),
    ]
