# Generated by Django 3.0.2 on 2020-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200516_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='tz',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
