# Generated by Django 3.1.4 on 2021-03-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200516_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatname', models.CharField(default='NULL', max_length=50)),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subsub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsubname', models.CharField(default='NULL', max_length=50)),
                ('subsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
